import { Analytics } from "@vercel/analytics/next"
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/*
        <nav style={{ 
          padding: "16px", 
          background: "#1a1a1a", 
          borderBottom: "1px solid #333",
          display: "flex",
          gap: "16px"
        }}>
          <a href="/" style={{ color: "#ddd", textDecoration: "none", padding: "8px 16px", borderRadius: "4px", background: "#333" }}>
            Visual Memory
          </a>
          <a href="/induction" style={{ color: "#ddd", textDecoration: "none", padding: "8px 16px", borderRadius: "4px", background: "#333" }}>
            Pattern Induction
          </a>
          <a href="/numeracy" style={{ color: "#ddd", textDecoration: "none", padding: "8px 16px", borderRadius: "4px", background: "#333" }}>
            Numeracy Trainer
          </a>
        </nav>
        */}
        {children}
        <Analytics/>
      </body>
    </html>
  );
}
